export const MOCK_DATA = [
  {
    id: 1,
    protein: 'TP53',
    canonical_name: 'Tumor protein p53',
    cell_line: 'HeLa',
    organism: 'Homo sapiens',
    molecular_weight_kda: 53,
    antibody: 'DO-1 (Santa Cruz sc-126)',
    condition: 'Doxorubicin 1μM, 24h',
    result: 'upregulated',
    confidence: 0.92,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'Western blot showing p53 expression levels',
    paper_pmid: '34567890',
    paper_title: 'Doxorubicin induces p53-dependent apoptosis in HeLa cells',
    paper_year: 2023,
  },
  {
    id: 2,
    protein: 'TP53',
    canonical_name: 'Tumor protein p53',
    cell_line: 'MCF-7',
    organism: 'Homo sapiens',
    molecular_weight_kda: 53,
    antibody: 'DO-1 (Santa Cruz sc-126)',
    condition: 'Untreated',
    result: 'detected',
    confidence: 0.88,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'p53 expression in MCF-7 breast cancer cells',
    paper_pmid: '34567891',
    paper_title: 'p53 mutational status and chemotherapy response',
    paper_year: 2023,
  },
  {
    id: 3,
    protein: 'TP53',
    canonical_name: 'Tumor protein p53',
    cell_line: 'HCT116',
    organism: 'Homo sapiens',
    molecular_weight_kda: 53,
    antibody: 'DO-1 (Santa Cruz sc-126)',
    condition: '5-FU treatment',
    result: 'upregulated',
    confidence: 0.94,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: '5-FU induced p53 upregulation in colon cancer',
    paper_pmid: '34567892',
    paper_title: 'Chemotherapy-induced p53 activation pathway',
    paper_year: 2022,
  },
  {
    id: 4,
    protein: 'TP53',
    canonical_name: 'Tumor protein p53',
    cell_line: 'U2OS',
    organism: 'Homo sapiens',
    molecular_weight_kda: 53,
    antibody: 'DO-1 (Santa Cruz sc-126)',
    condition: 'Gamma irradiation (10 Gy)',
    result: 'upregulated',
    confidence: 0.96,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'Radiation-induced p53 response in osteosarcoma cells',
    paper_pmid: '34567893',
    paper_title: 'DNA damage response: p53 activation after irradiation',
    paper_year: 2023,
  },
  {
    id: 5,
    protein: 'GAPDH',
    canonical_name: 'Glyceraldehyde 3-phosphate dehydrogenase',
    cell_line: 'HeLa',
    organism: 'Homo sapiens',
    molecular_weight_kda: 37,
    antibody: 'Loading control (Sigma)',
    condition: 'Untreated',
    result: 'detected',
    confidence: 0.99,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'GAPDH loading control expression',
    paper_pmid: '34567894',
    paper_title: 'Standardizing loading control normalization in Western blots',
    paper_year: 2023,
  },
  {
    id: 6,
    protein: 'GAPDH',
    canonical_name: 'Glyceraldehyde 3-phosphate dehydrogenase',
    cell_line: 'MCF-7',
    organism: 'Homo sapiens',
    molecular_weight_kda: 37,
    antibody: 'Loading control (Sigma)',
    condition: 'Untreated',
    result: 'detected',
    confidence: 0.99,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'GAPDH loading control',
    paper_pmid: '34567895',
    paper_title: 'Protein normalization strategies for Western blotting',
    paper_year: 2022,
  },
  {
    id: 7,
    protein: 'BRCA1',
    canonical_name: 'Breast cancer type 1 susceptibility protein',
    cell_line: 'MCF-7',
    organism: 'Homo sapiens',
    molecular_weight_kda: 220,
    antibody: 'MS110 (Calbiochem)',
    condition: 'Untreated',
    result: 'detected',
    confidence: 0.85,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'BRCA1 protein expression in wild-type MCF-7',
    paper_pmid: '34567896',
    paper_title: 'BRCA1 expression levels and cancer risk assessment',
    paper_year: 2023,
  },
  {
    id: 8,
    protein: 'BRCA1',
    canonical_name: 'Breast cancer type 1 susceptibility protein',
    cell_line: 'HEK293',
    organism: 'Homo sapiens',
    molecular_weight_kda: 220,
    antibody: 'MS110 (Calbiochem)',
    condition: 'Ionizing radiation (8 Gy)',
    result: 'upregulated',
    confidence: 0.87,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'IR-induced BRCA1 upregulation in HEK293T cells',
    paper_pmid: '34567897',
    paper_title: 'BRCA1 activation in DNA damage response',
    paper_year: 2022,
  },
  {
    id: 9,
    protein: 'EGFR',
    canonical_name: 'Epidermal growth factor receptor',
    cell_line: 'A549',
    organism: 'Homo sapiens',
    molecular_weight_kda: 170,
    antibody: 'D38B1 (Cell Signaling)',
    condition: 'EGF stimulation (100 ng/mL, 5 min)',
    result: 'upregulated',
    confidence: 0.91,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'EGF-induced EGFR phosphorylation in lung cancer cells',
    paper_pmid: '34567898',
    paper_title: 'EGFR signaling pathway activation in NSCLC',
    paper_year: 2023,
  },
  {
    id: 10,
    protein: 'EGFR',
    canonical_name: 'Epidermal growth factor receptor',
    cell_line: 'HCT116',
    organism: 'Homo sapiens',
    molecular_weight_kda: 170,
    antibody: 'D38B1 (Cell Signaling)',
    condition: 'Gefitinib treatment (1 μM, 24h)',
    result: 'downregulated',
    confidence: 0.89,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'EGFR inhibition by gefitinib in colorectal cancer',
    paper_pmid: '34567899',
    paper_title: 'EGFR inhibitor response in CRC cell lines',
    paper_year: 2023,
  },
  {
    id: 11,
    protein: 'AKT',
    canonical_name: 'RAC-alpha serine/threonine-protein kinase',
    cell_line: 'MCF-7',
    organism: 'Homo sapiens',
    molecular_weight_kda: 60,
    antibody: 'C67E7 (Cell Signaling)',
    condition: 'Insulin stimulation (100 nM, 10 min)',
    result: 'upregulated',
    confidence: 0.93,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'Insulin-stimulated Akt phosphorylation',
    paper_pmid: '34567900',
    paper_title: 'PI3K/Akt pathway in metabolic signaling',
    paper_year: 2023,
  },
  {
    id: 12,
    protein: 'AKT',
    canonical_name: 'RAC-alpha serine/threonine-protein kinase',
    cell_line: 'HeLa',
    organism: 'Homo sapiens',
    molecular_weight_kda: 60,
    antibody: 'C67E7 (Cell Signaling)',
    condition: 'PI3K inhibitor (LY294002, 10 μM)',
    result: 'downregulated',
    confidence: 0.90,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'PI3K-dependent Akt inhibition',
    paper_pmid: '34567901',
    paper_title: 'PI3K/Akt signaling in cell survival',
    paper_year: 2022,
  },
  {
    id: 13,
    protein: 'ERK',
    canonical_name: 'Extracellular signal-regulated kinase 1/2',
    cell_line: 'HEK293',
    organism: 'Homo sapiens',
    molecular_weight_kda: 44,
    antibody: 'E344 (Cell Signaling)',
    condition: 'EGF stimulation (50 ng/mL, 5 min)',
    result: 'upregulated',
    confidence: 0.95,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'EGF-induced ERK1/2 phosphorylation',
    paper_pmid: '34567902',
    paper_title: 'MAPK/ERK pathway in growth factor signaling',
    paper_year: 2023,
  },
  {
    id: 14,
    protein: 'ERK',
    canonical_name: 'Extracellular signal-regulated kinase 1/2',
    cell_line: 'U2OS',
    organism: 'Homo sapiens',
    molecular_weight_kda: 44,
    antibody: 'E344 (Cell Signaling)',
    condition: 'MEK inhibitor (U0126, 20 μM)',
    result: 'downregulated',
    confidence: 0.92,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'MEK/ERK pathway inhibition',
    paper_pmid: '34567903',
    paper_title: 'MAPK inhibition as cancer therapeutic',
    paper_year: 2023,
  },
  {
    id: 15,
    protein: 'beta-actin',
    canonical_name: 'Actin, beta',
    cell_line: 'A549',
    organism: 'Homo sapiens',
    molecular_weight_kda: 42,
    antibody: 'AC-74 (Sigma)',
    condition: 'Untreated',
    result: 'detected',
    confidence: 0.99,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'Beta-actin loading control',
    paper_pmid: '34567904',
    paper_title: 'Cytoskeletal protein normalization',
    paper_year: 2023,
  },
  {
    id: 16,
    protein: 'beta-actin',
    canonical_name: 'Actin, beta',
    cell_line: 'CHO',
    organism: 'Cricetulus griseus',
    molecular_weight_kda: 42,
    antibody: 'AC-74 (Sigma)',
    condition: 'Untreated',
    result: 'detected',
    confidence: 0.99,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'Beta-actin in mammalian expression systems',
    paper_pmid: '34567905',
    paper_title: 'Protein expression in CHO cell lines',
    paper_year: 2022,
  },
  {
    id: 17,
    protein: 'Tubulin',
    canonical_name: 'Alpha tubulin',
    cell_line: 'HepG2',
    organism: 'Homo sapiens',
    molecular_weight_kda: 55,
    antibody: 'TUB 2.1 (Sigma)',
    condition: 'Untreated',
    result: 'detected',
    confidence: 0.98,
    figure_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=100&h=100&fit=crop',
    caption: 'Alpha-tubulin loading control',
    paper_pmid: '34567906',
    paper_title: 'Tubulin as reference protein for Western blots',
    paper_year: 2023,
  },
];
